-- Wordpress
CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'wpadmin'@'%' IDENTIFIED BY '6wc4Pmjm';
GRANT ALL PRIVILEGES ON wordpress.* TO 'wpadmin'@'%';
FLUSH PRIVILEGES;

-- Moodle
CREATE DATABASE IF NOT EXISTS moodle DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;;
CREATE USER IF NOT EXISTS 'moodle'@'%' IDENTIFIED BY '4p6rCSPJ';
GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,CREATE TEMPORARY TABLES,DROP,INDEX,ALTER ON moodle.* TO 'moodle'@'%';
FLUSH PRIVILEGES;

-- Nextcloud
CREATE DATABASE IF NOT EXISTS nextcloud DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;;
CREATE USER IF NOT EXISTS 'nextcloud'@'%' IDENTIFIED BY 'gd9BD8U8';
GRANT ALL PRIVILEGES ON nextcloud.* TO 'nextcloud'@'%';
FLUSH PRIVILEGES;

