#!/bin/bash
set -e

psql -v ON_ERROR_STOP=0 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    DROP DATABASE IF EXISTS $POSTGRES_DB;
    DROP USER IF EXISTS $MOODLE_USER;
	CREATE USER $MOODLE_USER PASSWORD '$MOODLE_PASSWORD';
	CREATE DATABASE $POSTGRES_DB;
	GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $MOODLE_USER;
EOSQL
