-- Moodle
DROP USER IF EXISTS moodle;
DROP DATABASE IF EXISTS moodle;
CREATE USER moodle PASSWORD 'secret';
CREATE DATABASE moodle WITH OWNER moodle ENCODING 'UTF8' LC_COLLATE='ca_ES.utf8' LC_CTYPE='ca_ES.utf8' TEMPLATE=template0;
GRANT ALL PRIVILEGES ON DATABASE moodle TO moodle;
