version: '3'
services:
  #### Wordpress
  wordpress:
    build:
      context: .
      dockerfile: ./assets/dockerfiles/wordpress-dockerfile
    container_name: wordpress_dawm8
    restart: unless-stopped
    ports:
      - "9280:80"
    environment:
      - WORDPRESS_DB_HOST=dbmysql
      - WORDPRESS_DB_USER=wpadmin
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - APACHE_SERVER_NAME=wordpress-daw8.fornes.cat
    volumes:
      - /var/local/volumes/wordpress-data:/var/www/html
    depends_on:
      - dbmysql
    networks:
      - appnet
  #### Moodle
  moodle:
    build:
      context: .
      dockerfile: ./assets/dockerfiles/moodle-dockerfile
    container_name: moodle_dawm8
    restart: unless-stopped
    ports:
      - "9180:80"
    environment:
      - MOODLE_URL=https://moodle-daw8.fornes.cat
      - MOODLE_DATA_ROOT=/var/www/moodledata
      - APACHE_SERVER_NAME=moodle-daw8.fornes.cat
      - MOODLE_DB_PASSWORD=$MOODLE_DB_PASSWORD
    volumes:
      - /var/local/volumes/moodle-code:/var/www/html
      - /var/local/volumes/moodle-data:/var/www/moodledata
    depends_on:
      - dbmysql
    networks:
      - appnet
  #### Nextcloud (disc cloud)
  nextcloud:
    image: nextcloud
    restart: unless-stopped
    ports:
      - 9480:80
    depends_on:
      - dbmysql
    volumes:
      - /var/local/volumes/nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=$NEXTCLOUD_MYSQL_PASSWORD
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=dbmysql
      - TRUSTED_PROXIES=192.168.32.1
      - OVERWRITEHOST=nextcloud-daw8.fornes.cat
      - OVERWRITEPROTOCOL=https
      - OVERWRITECLIURL=https://nextcloud-daw8.fornes.cat
      - OVERWRITEWEBROOT=/
      - APACHE_SERVER_NAME=nextcloud-daw8.fornes.cat
    networks:
      - appnet
  #### Odoo
  odoo:
    build:
      context: .
      dockerfile: ./assets/dockerfiles/odoo-dockerfile
    container_name: odoo_dawm8
    depends_on:
      - dbpostgressql
    ports:
      - "9380:80"
    volumes:
      - /var/local/volumes/odoo-data:/var/lib/odoo
    environment:
      - HOST=dbpostgressql
      - PORT=5432
      - USER=odoo
      - PASSWORD=$POSTGRES_PASSWORD
      - DATABASE=odoodb
      - PROXYMODE=no
    networks:
      - appnet
  #### BASE DE DADES específica de odoo
  dbpostgressql:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=odoodb
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=odoo
    volumes:
      - /var/local/volumes/postgresql:/var/lib/postgresql/data
      - ./assets/scripts/init-postgres.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    restart: unless-stopped
    networks:
      - appnet
  #### BASE DE DADES COMUNA de wordpress, nextcloud i moodle
  dbmysql:
    image: mysql:5.7
    container_name: dbmysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    volumes:
      - /var/local/volumes/mysql-data:/var/lib/mysql
      - ./assets/scripts/init-sql.sh:/docker-entrypoint-initdb.d/init-sql.sh
    networks:
      - appnet
networks:
  appnet:
    driver: bridge
