version: '3'
services:
  #### Odoo
  odoo:
    build:
      context: .
      dockerfile: ./assets/dockerfiles/odoo-dockerfile
    container_name: odoo_dawm8
    depends_on:
      - dbpostgressql
    ports:
      - "9380:80"
    volumes:
      - /var/local/volumes/odoo-data:/var/lib/odoo
      # - ./assets/scripts/start-odoo.sh:/var/lib/odoo/start-odoo.sh
    environment:
      - HOST=dbpostgressql
      - PORT=5432
      - USER=odoo
      - PASSWORD=$ODOO_PWD
      - DATABASE=$ODOO_DATABASE
      - PROXYMODE=$ODOO_PROXY_MODE
      - LOGLEVEL=$ODOO_LOGLEVEL
    networks:
      - appnet
  #### BASE DE DADES específica de odoo
  dbpostgressql:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=postgresql
      - USER=odoo
      - PASSWORD=$ODOO_PWD
      - DATABASE=$ODOO_DATABASE
    volumes:
      - /var/local/volumes/postgresql:/var/lib/postgresql/data
      - ./assets/scripts/init-postgres.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    restart: unless-stopped
    networks:
      - appnet
networks:
  appnet:
    driver: bridge
